# Installation Directory
cask_args appdir: '/Applications'

# Browsers
cask 'firefox'
cask 'google-chrome'

# File Management
brew 'csvkit'
brew 'fzf'
brew 'helix'
brew 'jq'
brew 'sq'
brew 'zoxide'

# General Utilities
brew 'atuin'
brew 'lazygit'
brew 'node'
brew 'pnpm'

# Miscellaneous
brew 'fish'
brew 'frotz'

# Casks - Applications
cask '1password'
cask 'orbstack'
cask 'wezterm'
cask 'raycast'
cask 'sketch'
cask 'tableplus'
cask 'zed'

# Casks - Fonts
cask 'font-jetbrains-mono'

# Applications (via Mac App Store)
brew 'mas'
mas 'Tailscale', id: 1475387142
